name: Run Mixtral Inference

on:
  push:
    branches:
      - main

jobs:
  query_mixtral:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Query Hugging Face Mixtral Model
        run: |
          RESPONSE=$(curl -s -X POST "https://api-inference.huggingface.co/models/mistralai/Mixtral-8x7B-Instruct-v0.1" \
          -H "Authorization: Bearer ${{ secrets.HF_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "inputs": "can you write 350 words email on productivity and don't give me tips write by yourself using your creativity",
                "parameters": {
                  "max_new_tokens": 5000,
                  "do_sample": true,
                  "temperature": 0.7,
                  "top_k": 50,
                  "top_p": 0.95
                }
              }')

          echo "$RESPONSE" | jq -r '.[0].generated_text' | sed '1d'
